#pragma once
#ifndef COMMON
#define COMMON

const float SCREEN_WIDTH=1024;
const float SCREEN_HEIGHT=786;

enum EUserType{USERTYPE_SERVER=0,USERTYPE_CLIENT=1};
enum ECarState{CARSTATE_MOVING,CARSTATE_STOP,CARSTATE_DAMPING,CARSTATE_COLLIDED,CARSTATE_MOVINGREVERSE};
enum EGameState{GAMESTATE_INTRO,GAMESTATE_NEWGAME,GAMESTATE_CONNECTION,GAMESTATE_RUNNINGGAME,GAMESTATE_PAUSE,GAMESTATE_EXIT};
enum ERaceWinner{RACEWINNER_PLAYER1,RACEWINNER_PLAYER2,RACEWINNER_DRAW};
enum EGameAsset{GAMEASSET_ROAD,GAMEASSET_MUD,GAMEASSET_OIL,GAMEASSET_PEDESTRIAN_LEFT,GAMEASSET_PEDESTRIAN_RIGHT,GAMEASSET_ROADBLOCK,GAMEASSET_NPCCAR,GAMEASSET_FINISHLINE};
enum ECollisionType{COLLISIONTYPE_NONE,COLLISIONTYPE_MUD,COLLISIONTYPE_OIL,COLLISIONTYPE_PEDESTRIAN,COLLISIONTYPE_ROADBLOCK,COLLISIONTYPE_NPCCAR,COLLISIONTYPE_FINISHLINE};

static int gsUser=0;
static ERaceWinner eRaceWinner;

#endif
